# Generated by Django 3.2 on 2020-11-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCustomer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('emailCustomer', models.CharField(max_length=100)),
                ('phoneCustomer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOrder', models.DateTimeField()),
                ('shippedDate', models.DateTimeField()),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.customers')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stok', models.IntegerField()),
                ('discontinued', models.BooleanField()),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categories')),
            ],
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.order')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.products')),
            ],
        ),
    ]
